
GET http://localhost:3000/cats


###

//example POST request below
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


//docs for REST client plugin: https://github.com/Huachao/vscode-restclient/blob/master/README.md#usage
